version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Build started on 'date'
      - docker build -t nginx-app AWS_Cloud/pipeline/
      - docker tag nginx-app:latest ramyaashwin/nginx-app:latest
      - echo Logging in to Docker Hub
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - echo Pushing Docker image to Docker Hub
      - docker push ramyaashwin/nginx-app:latest
artifacts:
  files:
    - 'AWS_Cloud/pipeline/**/*'