version: 0.2
phases:
  build:
    commands:
      - echo Build started on 'date'
      - docker build -t nginx-app AWS Cloud/pipeline/
      - docker tag nginx-app:latest ramyaashwin/nginx-app:latest
artifacts:
  files:
    - 'AWS Cloud/pipeline/**/*'